### ISSUE TITLE
Targeting sub-schema doesn't work alone

### ISSUE THREAD

**Issue by toddbaert** [open-feature/flagd-schemas#165]
The [targeting sub-schema](https://flagd.dev/schema/v0/targeting.json) doesn't work if used by itself. It's entirely correct and works well if used as part of the [parent schema](https://flagd.dev/schema/v0/flags.json), but doesn't work in isolation.

This seems to be because we only DEFINE "targeting" in this schema, but don't use it to validate the top-level object. 

We need to:

- use the existing definition to validate the top-level object
- add 1 positive and 1 negative test to make sure the schema works as expected
  - we already have lots of test coverage [here](https://github.com/open-feature/flagd-schemas/blob/main/json/flagd_definitions_test.go) where we iterate over all the JSON in the `positive` and `negative` dirs as part of the parent, we just need this new single positive/negative test to load the targeting schema in isolation and make sure it works alone as well. This means a new test which loads just the targeting schema instead of the definition schema, similar to this line: https://github.com/open-feature/flagd-schemas/blob/61523e5efe3e4203032f75e41bb31c4cee189b48/json/flagd_definitions_test.go#L22

**Comment by toddbaert** [comment]
cc @aepfli

**Comment by aepfli** [comment]
Thank you for creating the bug - below i added a small spoiler for the changes to the targeting.json ;) 

<details>

<summary>behind this is a spoiler for the solution </summary>

At line 6 of the targeting.json we need to add an
 ```
  "type": "object",
  "anyOf": [
    {
      "$ref": "#/definitions/targeting"
    }
  ],
```
https://github.com/open-feature/flagd-schemas/blob/main/json/targeting.json#L6 



</details>
